### ISSUE TITLE
Problems with addon manager Ajour

### ISSUE THREAD

**Issue by Netspider** [ahakola/AlreadyKnown#4]
Hello,
Already known is not fully compatible with the addon manager [Ajour](https://www.getajour.com/). After installing the addon and clicking on "refresh" Ajour cannot find the current version number of this addon. Update notifications are not working because of this. It has something to do with the addon TOC-file(s).
Some links that might be helpful:

- https://github.com/ajour/ajour/wiki/How-Ajour-decides-which-source-to-use-for-updates
- https://github.com/ajour/ajour/wiki/Packaging-an-addon-for-Ajour

The addon [Attune](https://www.curseforge.com/wow/addons/attune) had the same problem but was fixed in version 233. All other addons I tried are working fine with this addon manager.

Finally I'd like to thank you for writing this addon, it really helps me :)
![1-installed](https://user-images.githubusercontent.com/347282/122064357-64fc4980-cdf1-11eb-8fe5-6266d26b1e44.png)
![2-refreshed](https://user-images.githubusercontent.com/347282/122064361-64fc4980-cdf1-11eb-99cd-1040e397151e.png)

**Comment by ahakola** [comment]
I would assume the error is more in the Ajour's end, because as far as I know, both the .toc and the new -BCC.toc files are properly formated, the packaging and uploading is done by the BigWigs packager script and I haven't heard any complaint from users of other addon managers. Have you tried reinstalling the addon from `Catalog` or `Install from URL`?

One possible cause of this issue might be that when I first created this addon and uploaded it to Curseforge, I didn't do name collision check and wasn't aware there already was addon with same name in WoWInterface. The other addon haven't been updated since MoP if I recall correctly, and that has caused people to send me some bogus error reports from that old, abandoned addon.

**Comment by ahakola** [comment]
Doing more research and it might be also something to do with Curseforge API not handling the different versions (Retail, Classic, BCClassic) very well. Apparently the website shows different version properly, but the addon manager API doesn't support it very well.

**Comment by Netspider** [comment]
@casperstorm do you see an issue with ajour or AlreadyKnown?

**Comment by casperstorm** [comment]
The issue is neither Ajour or AlreadyKnown but in fact a Curse problem. Not long ago it became possible to add multiple TOC files to a single addon, and while Curse is able to accept addons utilizing this, their API serving the addons isn't ready for it yet.

We saw the same problem with Attune, where the author edded up reverting to a single TOC:

> New separate versions uploaded to curse
it's a pain now as I need to edit the Attune.toc file twice. Curse doesn't accept having just Attune-BCC.toc or Attune-Classic.toc

@Netspider what you can do now though is to use Ajour's Install from URL and just paste `https://github.com/ahakola/AlreadyKnown`. It will grab the latest release from GitHub and use that.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/2248455/122168119-295a9180-ce7c-11eb-8a2b-89e8c982e6fa.png">

We talked with Curse about it, and they say its: "On their TODO".

**Comment by Netspider** [comment]
thanks for the workaround :-)
